const getters = {
  sidebar: (state) => state.app.sidebar,
  opened: (state) => state.app.sidebar.opened,
  device: (state) => state.app.device,
  themeColor: (state) => state.app.themeColor,
  pageTitle: (state) => state.app.pageTitle,
  visitedViews: (state) => state.tagsView.visitedViews,
  cachedViews: (state) => state.tagsView.cachedViews,
  token: (state) => state.user.token,
  status: (state) => state.user.status,
  roles: (state) => state.user.roles,
  userId: (state) => state.user.userId,
  userInfo: (state) => state.user.userInfo,
  setting: (state) => state.user.setting,
  department: (state) => state.user.department,
  userName: (state) => state.user.userName,
  routesMemoryList: (state) => state.tabs.routesMemoryList,
  menuMap: (state) => state.tabs.menuMap,
  menuIndexObj: (state) => state.tabs.menuIndexObj,
  moduleMenuIndex: (state) => state.tabs.moduleMenuIndex,
  secondMenuIndex: (state) => state.tabs.secondMenuIndex,
  currentPath: (state) => state.tabs.currentPath,
  unitReportTabsIndex: (state) => state.remberTags.unitReportTabsIndex,
  userBtnsViews: (state) => state.user.userBtnsViews,
  userTabsViews: (state) => state.user.userTabsViews,
  systemPermissionList: (state) => state.user.systemPermissionList,
  allOperationBehavior: (state) => state.remberTags.checkAllOperationBehavior,
  currentLang: (state) => state.app.currentLang,
  excludeCacheComponentsList: (state) => state.tabs.excludeCacheComponentsList,
  taskList: (state) => state.learnManager.taskList,
  totalTask: (state) => state.learnManager.totalTask,
  xgList: (state) =>
    state.user.xgAndGwListSet.filter((v) => v.roleName === "学管"),
  gwList: (state) =>
    state.user.xgAndGwListSet.filter((v) => v.roleName === "课程顾问"),
  skuAmount: (state) => state.system.skuAmount,
  userTimeZone: (state) => state.user.userTimeZone,
};
export default getters;
